version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis_data:/data
  hotspot-backend:
    container_name: hotspot-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    restart: always
volumes:
  redis_data:
   driver: local